"use strict";
/******************************************************************************
*
* DO NOT EDIT THIS FILE.
*
* The contents of this file were generated by mergeSchemaExports.ts
*
******************************************************************************/
exports.__esModule = true;
exports.CoreRootType = "\ntype Query {\n  locations(searchText: String!): [Location]\n  eventById(id: ID!): Event\n  eventsForUser: [Event]\n  invitationsForEvent(eventId: ID!): [Invitation]\n}\ntype Mutation {\n  inviteUserToEvent(cliqId: ID!, name: String!, email: String!): Boolean\n  resendInviteToEvent(invitationId: ID!): Boolean\n  createEvent(type: EventType): Event\n  updateEventLocation(eventId: ID!, locationId: ID!): Event\n  updatePendingParticipants(eventId: ID!, participants: [ID!]!): Event\n  updateParticipants(eventId: ID!, participants: [ID!]!): Event\n  acceptInvitation(invitationId: ID!, code: ID!): Event\n}\n";
exports.UserRootType = "\ntype Query {\n  me: User\n  friends: [User]\n}\ntype Mutation {\n  signup(name: String!, email: String!, password: String!): AuthPayload!\n  login(email: String!, password: String!): AuthPayload!\n}\n";
