/******************************************************************************
*
* DO NOT EDIT THIS FILE.
*
* The contents of this file were generated by mergeSchemaExports.ts
*
******************************************************************************/
export declare const CoreRootType = "\ntype Query {\n  locations(searchText: String!): [Location]\n}\n";
export declare const UserRootType = "\ntype Query {\n  me: User\n}\ntype Mutation {\n  signup(name: String!, email: String!, password: String!): AuthPayload!\n  login(email: String!, password: String!): AuthPayload!\n}\n";
