/******************************************************************************
*
* DO NOT EDIT THIS FILE.
*
* The contents of this file were generated by mergeSchemaExports.ts
*
******************************************************************************/
export declare const CoreRootType = "\ntype Query {\n  locations(searchText: String!): [Location]\n  eventById(id: ID!): Event\n  eventsForUser: [Event]\n}\ntype Mutation {\n  createEvent(type: EventType): Event\n  updateEventLocation(eventId: ID!, locationId: ID!): Event\n  updateParticipants(cliqId: ID!, participants: [ID!]!): Boolean\n}\n";
export declare const UserRootType = "\ntype Query {\n  me: User\n  friends: [User]\n  invitationsForEvent(eventId: ID!): [Invitation]\n}\ntype Mutation {\n  signup(name: String!, email: String!, password: String!): AuthPayload!\n  login(email: String!, password: String!): AuthPayload!\n  inviteUserToEvent(eventId: ID!, name: String!, email: String!): ID\n  resendInviteToEvent(invitationId: ID!): Boolean\n  acceptInvitation(invitationId: ID!, code: ID!): Event\n}\n";
