"use strict";
/******************************************************************************
*
* DO NOT EDIT THIS FILE.
*
* The contents of this file were generated by mergeSchemaExports.ts
*
******************************************************************************/
exports.__esModule = true;
exports.CoreRootType = "\ntype Query {\n  locations(searchText: String!): [Location]\n  eventById(id: ID!): Event\n  eventsForUser: [Event]\n  me: User\n  friends: [User]\n  invitationDetails(invitationId: ID!): InvitationEventPayload\n  invitationById(invitationId: ID!): Invitation\n  invitationsForEvent(eventId: ID!): [Invitation]\n}\ntype Mutation {\n  signup(name: String!, email: String!, password: String!): AuthPayload!\n  login(email: String!, password: String!): AuthPayload!\n  createEvent(type: EventType): Event\n  updateEventLocation(eventId: ID!, locationId: ID!): Event\n  updateParticipants(cliqId: ID!, participants: [ID!]!): Boolean\n  inviteUserToEvent(eventId: ID!, name: String!, email: String!): ID\n  resendInviteToEvent(invitationId: ID!): Boolean\n  acceptInvitationForNewUser(\n    invitationId: ID!\n    password: String!\n    code: String!\n  ): InvitationPayload!\n  acceptInvitationForExistingUser(\n    invitationId: ID!\n    code: String!\n  ): InvitationPayload!\n}\n";
