"use strict";
/******************************************************************************
*
* DO NOT EDIT THIS FILE.
*
* The contents of this file were generated by generateTypeDefinitions.ts
*
******************************************************************************/
exports.__esModule = true;
var CompensationType = {
    SALARY: 'SALARY'
};
exports["default"] = CompensationType;
