/******************************************************************************
*
* DO NOT EDIT THIS FILE.
*
* The contents of this file were generated by generateTypeDefinitions.ts
*
******************************************************************************/
declare const CSODRequisitionStatus: {
    DRAFT: string;
    OPEN: string;
    CLOSED: string;
    CANCELLED: string;
    PENDING_APPROVAL: string;
    APPROVAL_DENIED: string;
    PENDING_REAPPROVAL: string;
    ON_HOLD: string;
};
export default CSODRequisitionStatus;
