"use strict";
/******************************************************************************
*
* DO NOT EDIT THIS FILE.
*
* The contents of this file were generated by generateTypeDefinitions.ts
*
******************************************************************************/
exports.__esModule = true;
var CSODRequisitionStatus = {
    DRAFT: 'DRAFT',
    OPEN: 'OPEN',
    CLOSED: 'CLOSED',
    CANCELLED: 'CANCELLED',
    PENDING_APPROVAL: 'PENDING_APPROVAL',
    APPROVAL_DENIED: 'APPROVAL_DENIED',
    PENDING_REAPPROVAL: 'PENDING_REAPPROVAL',
    ON_HOLD: 'ON_HOLD'
};
exports["default"] = CSODRequisitionStatus;
