"use strict";
/******************************************************************************
*
* DO NOT EDIT THIS FILE.
*
* The contents of this file were generated by generateTypeDefinitions.ts
*
******************************************************************************/
exports.__esModule = true;
var CurrencyType = {
    USD: 'USD'
};
exports["default"] = CurrencyType;
