/******************************************************************************
*
* DO NOT EDIT THIS FILE.
*
* The contents of this file were generated by generateTypeDefinitions.ts
*
******************************************************************************/
declare const CurrencyType: {
    USD: string;
};
export default CurrencyType;
