"use strict";
/******************************************************************************
*
* DO NOT EDIT THIS FILE.
*
* The contents of this file were generated by generateTypeDefinitions.ts
*
******************************************************************************/
exports.__esModule = true;
var EventStatus = {
    COMPLETED: 'COMPLETED',
    PLANNED: 'PLANNED',
    INCOMPLETE: 'INCOMPLETE',
    CANCELLED: 'CANCELLED'
};
exports["default"] = EventStatus;
