/******************************************************************************
*
* DO NOT EDIT THIS FILE.
*
* The contents of this file were generated by generateTypeDefinitions.ts
*
******************************************************************************/
declare const EventType: {
    HAPPY_HOUR: string;
};
export default EventType;
