"use strict";
/******************************************************************************
*
* DO NOT EDIT THIS FILE.
*
* The contents of this file were generated by generateTypeDefinitions.ts
*
******************************************************************************/
exports.__esModule = true;
var EventType = {
    HAPPY_HOUR: 'HAPPY_HOUR'
};
exports["default"] = EventType;
