/******************************************************************************
*
* DO NOT EDIT THIS FILE.
*
* The contents of this file were generated by generateTypeDefinitions.ts
*
******************************************************************************/
declare const EventStatus: {
    COMPLETED: string;
    PLANNED: string;
    INCOMPLETE: string;
    CANCELLED: string;
};
export default EventStatus;
