/******************************************************************************
*
* DO NOT EDIT THIS FILE.
*
* The contents of this file were generated by generateTypeDefinitions.ts
*
******************************************************************************/
declare const StateCodes: {
    CA: string;
};
export default StateCodes;
