"use strict";
/******************************************************************************
*
* DO NOT EDIT THIS FILE.
*
* The contents of this file were generated by generateTypeDefinitions.ts
*
******************************************************************************/
exports.__esModule = true;
var TodoStatus = {
    INCOMPLETE: 'INCOMPLETE',
    COMPLETE: 'COMPLETE'
};
exports["default"] = TodoStatus;
