/******************************************************************************
*
* DO NOT EDIT THIS FILE.
*
* The contents of this file were generated by generateTypeDefinitions.ts
*
******************************************************************************/
declare const TodoStatus: {
    INCOMPLETE: string;
    COMPLETE: string;
};
export default TodoStatus;
