// ============================================================================
        // DO NOT EDIT.
        // The contents of this file are generated by merging types exported from
        // src/Schemas/index.js
        // ============================================================================
        export default `
schema {
  query: Query
  mutation: Mutation
}

type Query {
  locations(searchText: String!): [Location]
  eventById(id: ID!): Event
  eventsForUser: [Event]
  me: User
  friends: [User]
  invitationsForEvent(eventId: ID!): [Invitation]
}

type Mutation {
  createEvent(type: EventType): Event
  updateEventLocation(eventId: ID!, locationId: ID!): Event
  updateParticipants(eventId: ID!, participants: [ID!]!): Event
  signup(name: String!, email: String!, password: String!): AuthPayload!
  login(email: String!, password: String!): AuthPayload!
  inviteUserToEvent(eventId: ID!, name: String!, email: String!): ID
  resendInviteToEvent(invitationId: ID!): Boolean
  acceptInvitation(invitationId: ID!, code: ID!): Event
}
`;
        