/******************************************************************************
 *
 * DO NOT EDIT THIS FILE.
 *
 * The contents of this file were generated by generateTypeDefinitions.ts
 *
 ******************************************************************************/

const Address = `
type Address {
  address1: String
  address2: String
  address3: String
  city: String
  zipcode: String
  country: String
  state: String
}
`;

const Location = `
type Location {
  id: ID!
  url: String
  name: String!
  address: Address
  avatar: String
  rating: Float
  reviewCount: Int
}
`;

const AuthPayload = `
type AuthPayload {
  token: String!
  user: User!
}
`;

const User = `
type User {
  id: ID!
  email: String!
  name: String!
  phone: String
  location: Address
}
`;

export default {
  Address,
  Location,
  AuthPayload,
  User
};
