/******************************************************************************
 *
 * DO NOT EDIT THIS FILE.
 *
 * The contents of this file were generated by generateTypeDefinitions.ts
 *
 ******************************************************************************/

const searchLocations = `query searchLocations($searchText: String!) {
  locations(searchText: $searchText) {
    id
    name
    avatar
    rating
    reviewCount
    url
    address {
      address1
      address2
      city
      country
      zipcode
      state
    }
  }
}`;

export default {
  searchLocations
};
