/******************************************************************************
 *
 * DO NOT EDIT THIS FILE.
 *
 * The contents of this file were generated by generateTypeDefinitions.ts
 *
 ******************************************************************************/

const searchLocations = `query searchLocations($searchText: String!) {
  locations(searchText: $searchText) {
    id
    name
    avatar
    rating
    reviewCount
    url
    address {
      address1
      address2
      city
      country
      zipcode
      state
    }
  }
}`;
const login = `mutation login($email: String!, $password: String!) {
  login(email: $email, password: $password) {
    user {
      id
      name
      email
    }
    token
  }
}`;
const signup = `mutation signup($name: String!, $email: String!, $password: String!) {
  signup(name: $name, email: $email, password: $password) {
    user {
      id
      name
      email
    }
    token
  }
}`;

export default {
  searchLocations,
  login,
  signup
};
