/******************************************************************************
 *
 * DO NOT EDIT THIS FILE.
 *
 * The contents of this file were generated by generateTypeDefinitions.ts
 *
 ******************************************************************************/
declare const _default: {
    searchLocations: string;
    friends: string;
    login: string;
    me: string;
    signup: string;
};
export default _default;
