import * as fs from 'fs';
import { fileLoader, mergeTypes } from 'merge-graphql-schemas';
import * as path from 'path';

// merge all types from the Schemas directory and combine them
// into a single RootType.ts

const PRESENTATION_ROOT_TYPE_PATH = path.resolve('./src/Schemas/presentation');

const COMBINED_ROOT_TYPE_PATH = path.resolve('./src/RootType.ts');
const frontEndTypesArray = fileLoader(PRESENTATION_ROOT_TYPE_PATH);

const mergedRootTypes = mergeTypes([...frontEndTypesArray]);

const mergedRootTypeFileContent = `// ============================================================================
// DO NOT EDIT.
// The contents of this file are generated by merging types exported from
// src/Schemas/index.js
// ============================================================================
export default \`\n${mergedRootTypes}\`;
`;

fs.writeFileSync(COMBINED_ROOT_TYPE_PATH, mergedRootTypeFileContent);
