"use strict";
exports.__esModule = true;
// ============================================================================
// DO NOT EDIT.
// The contents of this file are generated by merging types exported from
// src/Schemas/index.js
// ============================================================================
exports["default"] = "\nschema {\n  query: Query\n  mutation: Mutation\n}\n\ntype Query {\n  locations(searchText: String!): [Location]\n  me: User\n}\n\ntype Mutation {\n  signup(name: String!, email: String!, password: String!): AuthPayload!\n  login(email: String!, password: String!): AuthPayload!\n}\n";
