/******************************************************************************
 *
 * DO NOT EDIT THIS FILE.
 *
 * The contents of this file were generated by generateTypeDefinitions.ts
 *
 ******************************************************************************/
declare const _default: {
    Address: string;
    Location: string;
    AuthPayload: string;
    User: string;
};
export default _default;
