/******************************************************************************
 *
 * DO NOT EDIT THIS FILE.
 *
 * The contents of this file were generated by generateTypeDefinitions.ts
 *
 ******************************************************************************/
declare const _default: {
    Address: string;
    Event: string;
    EventStatus: string;
    EventType: string;
    Location: string;
    AuthPayload: string;
    Invitation: string;
    InvitationEventPayload: string;
    InvitationPayload: string;
    User: string;
};
export default _default;
