
/******************************************************************************
*
* DO NOT EDIT THIS FILE.
*
* The contents of this file were generated by generateServiceBindings.ts
*
******************************************************************************/

  import { UserRootType } from '../Schemas'
  import ServiceBinding, { buildRootSchema } from './Binding';

  interface ICreateBinding {
    uri: string,
    headersToForward: string[]
  }

  export default function UserRootTypeBinding({ uri, headersToForward }: ICreateBinding) {
    return new ServiceBinding({
      typeDefs: buildRootSchema(UserRootType),
      uri,
      headersToForward,
    });
  }
