
/******************************************************************************
*
* DO NOT EDIT THIS FILE.
*
* The contents of this file were generated by generateTypeDefinitions.ts
*
******************************************************************************/

const CompensationType = {
  SALARY: 'SALARY',
};

export default CompensationType;
