
/******************************************************************************
*
* DO NOT EDIT THIS FILE.
*
* The contents of this file were generated by generateTypeDefinitions.ts
*
******************************************************************************/

const CountryCodes = {
  USA: 'USA',
};

export default CountryCodes;
