
/******************************************************************************
*
* DO NOT EDIT THIS FILE.
*
* The contents of this file were generated by generateTypeDefinitions.ts
*
******************************************************************************/

const CurrencyType = {
  USD: 'USD',
};

export default CurrencyType;
