
/******************************************************************************
*
* DO NOT EDIT THIS FILE.
*
* The contents of this file were generated by generateTypeDefinitions.ts
*
******************************************************************************/

const EventStatus = {
  COMPLETED: 'COMPLETED',
  PLANNED: 'PLANNED',
  INCOMPLETE: 'INCOMPLETE',
  CANCELLED: 'CANCELLED',
};

export default EventStatus;
