
/******************************************************************************
*
* DO NOT EDIT THIS FILE.
*
* The contents of this file were generated by generateTypeDefinitions.ts
*
******************************************************************************/

const EventType = {
  HAPPY_HOUR: 'HAPPY_HOUR',
};

export default EventType;
