
/******************************************************************************
*
* DO NOT EDIT THIS FILE.
*
* The contents of this file were generated by generateTypeDefinitions.ts
*
******************************************************************************/

const StateCodes = {
  CA: 'CA',
};

export default StateCodes;
