
/******************************************************************************
*
* DO NOT EDIT THIS FILE.
*
* The contents of this file were generated by mergeSchemaExports.ts
*
******************************************************************************/

  export const CoreRootType = `
type Query {
  locations(searchText: String!): [Location]
}
`;

export const UserRootType = `
type Query {
  me: User
}
type Mutation {
  signup(name: String!, email: String!, password: String!): AuthPayload!
  login(email: String!, password: String!): AuthPayload!
}
`;


