"use strict";
/******************************************************************************
*
* DO NOT EDIT THIS FILE.
*
* The contents of this file were generated by generateServiceBindings.ts
*
******************************************************************************/
exports.__esModule = true;
var Schemas_1 = require("../Schemas");
var Binding_1 = require("./Binding");
function UserRootTypeBinding(_a) {
    var uri = _a.uri, headersToForward = _a.headersToForward;
    return new Binding_1["default"]({
        typeDefs: Binding_1.buildRootSchema(Schemas_1.UserRootType),
        uri: uri,
        headersToForward: headersToForward
    });
}
exports["default"] = UserRootTypeBinding;
