/******************************************************************************
*
* DO NOT EDIT THIS FILE.
*
* The contents of this file were generated by generateServiceBindings.ts
*
******************************************************************************/
import ServiceBinding from './Binding';
interface ICreateBinding {
    uri: string;
    headersToForward: string[];
}
export default function UserRootTypeBinding({ uri, headersToForward }: ICreateBinding): ServiceBinding;
export {};
